spring:
  application:
    name: Lab 3 Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quickheaven/SpringCloudServerConfiguration
          searchPaths: ConfigData
      native:
        searchLocations: classpath:offline-repository/

server:
  port: 8001

logging.level:
  org.springframework.cloud.config.server:
    environment.MultipleJGitEnvironmentRepository: WARN